# Generated by Django 5.1.4 on 2024-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_moved',
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
