# Generated by Django 5.1.4 on 2024-12-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_task_task_composite_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default='quokka', on_delete=django.db.models.deletion.CASCADE, to='frontend.user'),
        ),
    ]
