# Generated by Django 5.1.4 on 2025-01-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_rename_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
