# Generated by Django 5.1.4 on 2024-12-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[(0, 'Backlog'), (1, 'Today'), (2, 'In Progress'), (3, 'Done')], default=0)),
                ('date_created', models.DateTimeField()),
                ('date_assigned', models.DateTimeField(null=True)),
                ('date_moved', models.DateField(null=True)),
                ('date_done', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'description'), name='Task_composite_primary_key')],
            },
        ),
    ]
